#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename;

my $subcommand = shift @ARGV or die "Usage: context-manager {location}\n";
my $script_dir = dirname(__FILE__);

my %commands = (
    location => "$script_dir/context-manager.d/location",
);

die "Unknown subcommand: $subcommand\n" unless exists $commands{$subcommand};
exec $commands{$subcommand}, @ARGV or die "Failed to exec: $!\n";
